language: node_js
node_js: "6.9.5"
cache:
  directories:
  - node_modules
script:
  - npm test --coverage
  - npm run build
after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
  